spring:
  application:
    name: data-producer
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/probable-octo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
